// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHJ4JPnu_Z6k6Q3mnDwTPpc4wwPZzD-c',
    appId: '1:163901642130:web:5dd1d0ea4e86ca25c15d4b',
    messagingSenderId: '163901642130',
    projectId: 'test-firebase-f1a83',
    authDomain: 'test-firebase-f1a83.firebaseapp.com',
    storageBucket: 'test-firebase-f1a83.appspot.com',
    measurementId: 'G-ZJS10FY9E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUvolBykV_rje8mHQTjAcxmCFcOlkYdg',
    appId: '1:163901642130:android:c49bbf57fd315e44c15d4b',
    messagingSenderId: '163901642130',
    projectId: 'test-firebase-f1a83',
    storageBucket: 'test-firebase-f1a83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEWP8C91FZrBl2beP4uQV5K7lnqNCY4E',
    appId: '1:163901642130:ios:6954e3cefe9f9ac8c15d4b',
    messagingSenderId: '163901642130',
    projectId: 'test-firebase-f1a83',
    storageBucket: 'test-firebase-f1a83.appspot.com',
    iosBundleId: 'com.santiago.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEWP8C91FZrBl2beP4uQV5K7lnqNCY4E',
    appId: '1:163901642130:ios:b51245f092816774c15d4b',
    messagingSenderId: '163901642130',
    projectId: 'test-firebase-f1a83',
    storageBucket: 'test-firebase-f1a83.appspot.com',
    iosBundleId: 'com.santiago.crudFirebase.RunnerTests',
  );
}
